export default function TermsOfService(){
    return(
        <>
            Terms of Service

            Amarás a Dios sobre todas las cosas. Sólo existe un Dios, creador y todopoderoso, al que adorar. ...
            No tomarás el nombre de Dios en vano. ...
            Santificarás las fiestas. ...
            Honrarás a tu padre y a tu madre. ...
            No matarás. ...
            No cometerás actos impuros. ...
            No robarás. ...
            No darás falso testimonio ni mentirás.
        </>
    )
}