export default function TermsOfService(){
    return(
        <>

           <h1 className="">Terminos de Servicio</h1> 
           // Icono de libro, un martillo o etc...
           
           <h4>
                Amarás a Dios sobre todas las cosas. Sólo existe un Dios, creador y todopoderoso, al que adorar. ...
                No tomarás el nombre de Dios en vano. ...
                Santificarás las fiestas. ...
                Honrarás a tu padre y a tu madre. ...
                No matarás. ...
                No cometerás actos impuros. ...
                No robarás. ...
                No darás falso testimonio ni mentirás.
            </h4>

            <h3>
                Si logras ver casos que violen el reglamento de la plataforma, ayudanos
                manteniendo un ambiente limpio y reportando aquellos usuarios
            </h3>

            // Construir un reglamento para un ecomercio...


        </>
    )
}